# Префикс для работы с логерами (их настройки)
logging:
  # Зададим уровень логирования корневого логера
  level:
    # Будем фиксировать сообщения типа WARN (и все что выше ERROR и FATAL)
    root: INFO
    # Так же мы можем настроить логер для конкретного класса
    org:
      springframework:
        jdbc:
          core: TRACE
        security:
          web:
            FilterChainProxy: TRACE
  # Записываем лог в файл
  file.name: Logs/oldboy.log

  # Настроим подключение к БД
spring:
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  # Настроим свойства Hibernate
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ... My client ID on Google
            clientSecret: ... My client secret on Google
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
          github:
            clientId: ... My client ID on Github
            clientSecret: ... My client secret on Github
            redirectUri: http://localhost:8080/login/oauth2/code/github